[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/log/script.js"
  to = "https://plausible.io/js/script.file-downloads.outbound-links.js"
  status = 200
  force = true

[[redirects]]
  from = "/log/api/event"
  to = "https://plausible.io/api/event"
  status = 200
  force = true
