// This file is auto-generated by @hey-api/openapi-ts

export const CMIP6DatasetMetadataSchema = {
    properties: {
        variable_id: {
            type: 'string',
            title: 'Variable Id'
        },
        source_id: {
            type: 'string',
            title: 'Source Id'
        },
        experiment_id: {
            type: 'string',
            title: 'Experiment Id'
        },
        variant_label: {
            type: 'string',
            title: 'Variant Label'
        }
    },
    type: 'object',
    required: ['variable_id', 'source_id', 'experiment_id', 'variant_label'],
    title: 'CMIP6DatasetMetadata'
} as const;

export const DatasetSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        dataset_type: {
            type: 'string',
            title: 'Dataset Type'
        },
        metadata: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CMIP6DatasetMetadata'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'slug', 'dataset_type', 'metadata'],
    title: 'Dataset'
} as const;

export const DatasetCollectionSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/Dataset'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DatasetCollection'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MetricSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        provider: {
            type: 'string',
            title: 'Provider'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        }
    },
    type: 'object',
    required: ['id', 'provider', 'slug'],
    title: 'Metric',
    description: 'A unique metric'
} as const;

export const MetricExecutionSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        key: {
            type: 'string',
            title: 'Key'
        },
        results: {
            items: {
                '$ref': '#/components/schemas/MetricExecutionResult'
            },
            type: 'array',
            title: 'Results'
        },
        latest_result: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MetricExecutionResult'
                },
                {
                    type: 'null'
                }
            ]
        },
        metric: {
            '$ref': '#/components/schemas/Metric'
        }
    },
    type: 'object',
    required: ['id', 'key', 'results', 'latest_result', 'metric'],
    title: 'MetricExecution'
} as const;

export const MetricExecutionResultSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        dataset_hash: {
            type: 'string',
            title: 'Dataset Hash'
        },
        successful: {
            type: 'boolean',
            title: 'Successful'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'dataset_hash', 'successful', 'created_at', 'updated_at'],
    title: 'MetricExecutionResult'
} as const;

export const MetricExecutionsSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MetricExecution'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MetricExecutions'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;