// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { UtilsHealthCheckData, UtilsHealthCheckResponse, UtilsListExecutionsData, UtilsListExecutionsResponse, UtilsListExecutionsError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health Check
 */
export const utilsHealthCheck = <ThrowOnError extends boolean = false>(options?: Options<UtilsHealthCheckData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<UtilsHealthCheckResponse, unknown, ThrowOnError>({
        url: '/api/v1/utils/health-check/',
        ...options
    });
};

/**
 * List Executions
 * List the latest executions
 */
export const utilsListExecutions = <ThrowOnError extends boolean = false>(options?: Options<UtilsListExecutionsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<UtilsListExecutionsResponse, UtilsListExecutionsError, ThrowOnError>({
        url: '/api/v1/executions/',
        ...options
    });
};