/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContentRouteImport } from './routes/content/route'
import { Route as AppRouteImport } from './routes/_app/route'
import { Route as IndexImport } from './routes/index'
import { Route as ContentTermsOfUseImport } from './routes/content/terms-of-use'
import { Route as ContentPrivacyImport } from './routes/content/privacy'
import { Route as ContentAboutImport } from './routes/content/about'
import { Route as AppExplorerRouteImport } from './routes/_app/explorer/route'
import { Route as AppExplorerIndexImport } from './routes/_app/explorer/index'
import { Route as AppExecutionsIndexImport } from './routes/_app/executions.index'
import { Route as AppDiagnosticsIndexImport } from './routes/_app/diagnostics.index'
import { Route as AppDatasetsIndexImport } from './routes/_app/datasets.index'
import { Route as AppExplorerThemesImport } from './routes/_app/explorer/themes'
import { Route as AppExecutionsGroupIdImport } from './routes/_app/executions.$groupId'
import { Route as AppDatasetsSlugImport } from './routes/_app/datasets.$slug'
import { Route as AppDiagnosticsProviderSlugDiagnosticSlugRouteImport } from './routes/_app/diagnostics.$providerSlug.$diagnosticSlug/route'
import { Route as AppDiagnosticsProviderSlugDiagnosticSlugIndexImport } from './routes/_app/diagnostics.$providerSlug.$diagnosticSlug/index'
import { Route as AppDiagnosticsProviderSlugDiagnosticSlugValuesImport } from './routes/_app/diagnostics.$providerSlug.$diagnosticSlug/values'
import { Route as AppDiagnosticsProviderSlugDiagnosticSlugGroupsImport } from './routes/_app/diagnostics.$providerSlug.$diagnosticSlug/groups'
import { Route as AppDiagnosticsProviderSlugDiagnosticSlugFiguresImport } from './routes/_app/diagnostics.$providerSlug.$diagnosticSlug/figures'

// Create/Update Routes

const ContentRouteRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRoute,
} as any)

const AppRouteRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContentTermsOfUseRoute = ContentTermsOfUseImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => ContentRouteRoute,
} as any)

const ContentPrivacyRoute = ContentPrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ContentRouteRoute,
} as any)

const ContentAboutRoute = ContentAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => ContentRouteRoute,
} as any)

const AppExplorerRouteRoute = AppExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppExplorerIndexRoute = AppExplorerIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppExplorerRouteRoute,
} as any)

const AppExecutionsIndexRoute = AppExecutionsIndexImport.update({
  id: '/executions/',
  path: '/executions/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDiagnosticsIndexRoute = AppDiagnosticsIndexImport.update({
  id: '/diagnostics/',
  path: '/diagnostics/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDatasetsIndexRoute = AppDatasetsIndexImport.update({
  id: '/datasets/',
  path: '/datasets/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppExplorerThemesRoute = AppExplorerThemesImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AppExplorerRouteRoute,
} as any)

const AppExecutionsGroupIdRoute = AppExecutionsGroupIdImport.update({
  id: '/executions/$groupId',
  path: '/executions/$groupId',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDatasetsSlugRoute = AppDatasetsSlugImport.update({
  id: '/datasets/$slug',
  path: '/datasets/$slug',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppDiagnosticsProviderSlugDiagnosticSlugRouteRoute =
  AppDiagnosticsProviderSlugDiagnosticSlugRouteImport.update({
    id: '/diagnostics/$providerSlug/$diagnosticSlug',
    path: '/diagnostics/$providerSlug/$diagnosticSlug',
    getParentRoute: () => AppRouteRoute,
  } as any)

const AppDiagnosticsProviderSlugDiagnosticSlugIndexRoute =
  AppDiagnosticsProviderSlugDiagnosticSlugIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDiagnosticsProviderSlugDiagnosticSlugRouteRoute,
  } as any)

const AppDiagnosticsProviderSlugDiagnosticSlugValuesRoute =
  AppDiagnosticsProviderSlugDiagnosticSlugValuesImport.update({
    id: '/values',
    path: '/values',
    getParentRoute: () => AppDiagnosticsProviderSlugDiagnosticSlugRouteRoute,
  } as any)

const AppDiagnosticsProviderSlugDiagnosticSlugGroupsRoute =
  AppDiagnosticsProviderSlugDiagnosticSlugGroupsImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AppDiagnosticsProviderSlugDiagnosticSlugRouteRoute,
  } as any)

const AppDiagnosticsProviderSlugDiagnosticSlugFiguresRoute =
  AppDiagnosticsProviderSlugDiagnosticSlugFiguresImport.update({
    id: '/figures',
    path: '/figures',
    getParentRoute: () => AppDiagnosticsProviderSlugDiagnosticSlugRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRoute
    }
    '/_app/explorer': {
      id: '/_app/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof AppExplorerRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/content/about': {
      id: '/content/about'
      path: '/about'
      fullPath: '/content/about'
      preLoaderRoute: typeof ContentAboutImport
      parentRoute: typeof ContentRouteImport
    }
    '/content/privacy': {
      id: '/content/privacy'
      path: '/privacy'
      fullPath: '/content/privacy'
      preLoaderRoute: typeof ContentPrivacyImport
      parentRoute: typeof ContentRouteImport
    }
    '/content/terms-of-use': {
      id: '/content/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/content/terms-of-use'
      preLoaderRoute: typeof ContentTermsOfUseImport
      parentRoute: typeof ContentRouteImport
    }
    '/_app/datasets/$slug': {
      id: '/_app/datasets/$slug'
      path: '/datasets/$slug'
      fullPath: '/datasets/$slug'
      preLoaderRoute: typeof AppDatasetsSlugImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/executions/$groupId': {
      id: '/_app/executions/$groupId'
      path: '/executions/$groupId'
      fullPath: '/executions/$groupId'
      preLoaderRoute: typeof AppExecutionsGroupIdImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/explorer/themes': {
      id: '/_app/explorer/themes'
      path: '/themes'
      fullPath: '/explorer/themes'
      preLoaderRoute: typeof AppExplorerThemesImport
      parentRoute: typeof AppExplorerRouteImport
    }
    '/_app/datasets/': {
      id: '/_app/datasets/'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AppDatasetsIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/diagnostics/': {
      id: '/_app/diagnostics/'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof AppDiagnosticsIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/executions/': {
      id: '/_app/executions/'
      path: '/executions'
      fullPath: '/executions'
      preLoaderRoute: typeof AppExecutionsIndexImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/explorer/': {
      id: '/_app/explorer/'
      path: '/'
      fullPath: '/explorer/'
      preLoaderRoute: typeof AppExplorerIndexImport
      parentRoute: typeof AppExplorerRouteImport
    }
    '/_app/diagnostics/$providerSlug/$diagnosticSlug': {
      id: '/_app/diagnostics/$providerSlug/$diagnosticSlug'
      path: '/diagnostics/$providerSlug/$diagnosticSlug'
      fullPath: '/diagnostics/$providerSlug/$diagnosticSlug'
      preLoaderRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/diagnostics/$providerSlug/$diagnosticSlug/figures': {
      id: '/_app/diagnostics/$providerSlug/$diagnosticSlug/figures'
      path: '/figures'
      fullPath: '/diagnostics/$providerSlug/$diagnosticSlug/figures'
      preLoaderRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugFiguresImport
      parentRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugRouteImport
    }
    '/_app/diagnostics/$providerSlug/$diagnosticSlug/groups': {
      id: '/_app/diagnostics/$providerSlug/$diagnosticSlug/groups'
      path: '/groups'
      fullPath: '/diagnostics/$providerSlug/$diagnosticSlug/groups'
      preLoaderRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugGroupsImport
      parentRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugRouteImport
    }
    '/_app/diagnostics/$providerSlug/$diagnosticSlug/values': {
      id: '/_app/diagnostics/$providerSlug/$diagnosticSlug/values'
      path: '/values'
      fullPath: '/diagnostics/$providerSlug/$diagnosticSlug/values'
      preLoaderRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugValuesImport
      parentRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugRouteImport
    }
    '/_app/diagnostics/$providerSlug/$diagnosticSlug/': {
      id: '/_app/diagnostics/$providerSlug/$diagnosticSlug/'
      path: '/'
      fullPath: '/diagnostics/$providerSlug/$diagnosticSlug/'
      preLoaderRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugIndexImport
      parentRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugRouteImport
    }
  }
}

// Create and export the route tree

interface AppExplorerRouteRouteChildren {
  AppExplorerThemesRoute: typeof AppExplorerThemesRoute
  AppExplorerIndexRoute: typeof AppExplorerIndexRoute
}

const AppExplorerRouteRouteChildren: AppExplorerRouteRouteChildren = {
  AppExplorerThemesRoute: AppExplorerThemesRoute,
  AppExplorerIndexRoute: AppExplorerIndexRoute,
}

const AppExplorerRouteRouteWithChildren =
  AppExplorerRouteRoute._addFileChildren(AppExplorerRouteRouteChildren)

interface AppDiagnosticsProviderSlugDiagnosticSlugRouteRouteChildren {
  AppDiagnosticsProviderSlugDiagnosticSlugFiguresRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugFiguresRoute
  AppDiagnosticsProviderSlugDiagnosticSlugGroupsRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugGroupsRoute
  AppDiagnosticsProviderSlugDiagnosticSlugValuesRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugValuesRoute
  AppDiagnosticsProviderSlugDiagnosticSlugIndexRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugIndexRoute
}

const AppDiagnosticsProviderSlugDiagnosticSlugRouteRouteChildren: AppDiagnosticsProviderSlugDiagnosticSlugRouteRouteChildren =
  {
    AppDiagnosticsProviderSlugDiagnosticSlugFiguresRoute:
      AppDiagnosticsProviderSlugDiagnosticSlugFiguresRoute,
    AppDiagnosticsProviderSlugDiagnosticSlugGroupsRoute:
      AppDiagnosticsProviderSlugDiagnosticSlugGroupsRoute,
    AppDiagnosticsProviderSlugDiagnosticSlugValuesRoute:
      AppDiagnosticsProviderSlugDiagnosticSlugValuesRoute,
    AppDiagnosticsProviderSlugDiagnosticSlugIndexRoute:
      AppDiagnosticsProviderSlugDiagnosticSlugIndexRoute,
  }

const AppDiagnosticsProviderSlugDiagnosticSlugRouteRouteWithChildren =
  AppDiagnosticsProviderSlugDiagnosticSlugRouteRoute._addFileChildren(
    AppDiagnosticsProviderSlugDiagnosticSlugRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppExplorerRouteRoute: typeof AppExplorerRouteRouteWithChildren
  AppDatasetsSlugRoute: typeof AppDatasetsSlugRoute
  AppExecutionsGroupIdRoute: typeof AppExecutionsGroupIdRoute
  AppDatasetsIndexRoute: typeof AppDatasetsIndexRoute
  AppDiagnosticsIndexRoute: typeof AppDiagnosticsIndexRoute
  AppExecutionsIndexRoute: typeof AppExecutionsIndexRoute
  AppDiagnosticsProviderSlugDiagnosticSlugRouteRoute: typeof AppDiagnosticsProviderSlugDiagnosticSlugRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppExplorerRouteRoute: AppExplorerRouteRouteWithChildren,
  AppDatasetsSlugRoute: AppDatasetsSlugRoute,
  AppExecutionsGroupIdRoute: AppExecutionsGroupIdRoute,
  AppDatasetsIndexRoute: AppDatasetsIndexRoute,
  AppDiagnosticsIndexRoute: AppDiagnosticsIndexRoute,
  AppExecutionsIndexRoute: AppExecutionsIndexRoute,
  AppDiagnosticsProviderSlugDiagnosticSlugRouteRoute:
    AppDiagnosticsProviderSlugDiagnosticSlugRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface ContentRouteRouteChildren {
  ContentAboutRoute: typeof ContentAboutRoute
  ContentPrivacyRoute: typeof ContentPrivacyRoute
  ContentTermsOfUseRoute: typeof ContentTermsOfUseRoute
}

const ContentRouteRouteChildren: ContentRouteRouteChildren = {
  ContentAboutRoute: ContentAboutRoute,
  ContentPrivacyRoute: ContentPrivacyRoute,
  ContentTermsOfUseRoute: ContentTermsOfUseRoute,
}

const ContentRouteRouteWithChildren = ContentRouteRoute._addFileChildren(
  ContentRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteRouteWithChildren
  '/content': typeof ContentRouteRouteWithChildren
  '/explorer': typeof AppExplorerRouteRouteWithChildren
  '/content/about': typeof ContentAboutRoute
  '/content/privacy': typeof ContentPrivacyRoute
  '/content/terms-of-use': typeof ContentTermsOfUseRoute
  '/datasets/$slug': typeof AppDatasetsSlugRoute
  '/executions/$groupId': typeof AppExecutionsGroupIdRoute
  '/explorer/themes': typeof AppExplorerThemesRoute
  '/datasets': typeof AppDatasetsIndexRoute
  '/diagnostics': typeof AppDiagnosticsIndexRoute
  '/executions': typeof AppExecutionsIndexRoute
  '/explorer/': typeof AppExplorerIndexRoute
  '/diagnostics/$providerSlug/$diagnosticSlug': typeof AppDiagnosticsProviderSlugDiagnosticSlugRouteRouteWithChildren
  '/diagnostics/$providerSlug/$diagnosticSlug/figures': typeof AppDiagnosticsProviderSlugDiagnosticSlugFiguresRoute
  '/diagnostics/$providerSlug/$diagnosticSlug/groups': typeof AppDiagnosticsProviderSlugDiagnosticSlugGroupsRoute
  '/diagnostics/$providerSlug/$diagnosticSlug/values': typeof AppDiagnosticsProviderSlugDiagnosticSlugValuesRoute
  '/diagnostics/$providerSlug/$diagnosticSlug/': typeof AppDiagnosticsProviderSlugDiagnosticSlugIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteRouteWithChildren
  '/content': typeof ContentRouteRouteWithChildren
  '/content/about': typeof ContentAboutRoute
  '/content/privacy': typeof ContentPrivacyRoute
  '/content/terms-of-use': typeof ContentTermsOfUseRoute
  '/datasets/$slug': typeof AppDatasetsSlugRoute
  '/executions/$groupId': typeof AppExecutionsGroupIdRoute
  '/explorer/themes': typeof AppExplorerThemesRoute
  '/datasets': typeof AppDatasetsIndexRoute
  '/diagnostics': typeof AppDiagnosticsIndexRoute
  '/executions': typeof AppExecutionsIndexRoute
  '/explorer': typeof AppExplorerIndexRoute
  '/diagnostics/$providerSlug/$diagnosticSlug/figures': typeof AppDiagnosticsProviderSlugDiagnosticSlugFiguresRoute
  '/diagnostics/$providerSlug/$diagnosticSlug/groups': typeof AppDiagnosticsProviderSlugDiagnosticSlugGroupsRoute
  '/diagnostics/$providerSlug/$diagnosticSlug/values': typeof AppDiagnosticsProviderSlugDiagnosticSlugValuesRoute
  '/diagnostics/$providerSlug/$diagnosticSlug': typeof AppDiagnosticsProviderSlugDiagnosticSlugIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/content': typeof ContentRouteRouteWithChildren
  '/_app/explorer': typeof AppExplorerRouteRouteWithChildren
  '/content/about': typeof ContentAboutRoute
  '/content/privacy': typeof ContentPrivacyRoute
  '/content/terms-of-use': typeof ContentTermsOfUseRoute
  '/_app/datasets/$slug': typeof AppDatasetsSlugRoute
  '/_app/executions/$groupId': typeof AppExecutionsGroupIdRoute
  '/_app/explorer/themes': typeof AppExplorerThemesRoute
  '/_app/datasets/': typeof AppDatasetsIndexRoute
  '/_app/diagnostics/': typeof AppDiagnosticsIndexRoute
  '/_app/executions/': typeof AppExecutionsIndexRoute
  '/_app/explorer/': typeof AppExplorerIndexRoute
  '/_app/diagnostics/$providerSlug/$diagnosticSlug': typeof AppDiagnosticsProviderSlugDiagnosticSlugRouteRouteWithChildren
  '/_app/diagnostics/$providerSlug/$diagnosticSlug/figures': typeof AppDiagnosticsProviderSlugDiagnosticSlugFiguresRoute
  '/_app/diagnostics/$providerSlug/$diagnosticSlug/groups': typeof AppDiagnosticsProviderSlugDiagnosticSlugGroupsRoute
  '/_app/diagnostics/$providerSlug/$diagnosticSlug/values': typeof AppDiagnosticsProviderSlugDiagnosticSlugValuesRoute
  '/_app/diagnostics/$providerSlug/$diagnosticSlug/': typeof AppDiagnosticsProviderSlugDiagnosticSlugIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/content'
    | '/explorer'
    | '/content/about'
    | '/content/privacy'
    | '/content/terms-of-use'
    | '/datasets/$slug'
    | '/executions/$groupId'
    | '/explorer/themes'
    | '/datasets'
    | '/diagnostics'
    | '/executions'
    | '/explorer/'
    | '/diagnostics/$providerSlug/$diagnosticSlug'
    | '/diagnostics/$providerSlug/$diagnosticSlug/figures'
    | '/diagnostics/$providerSlug/$diagnosticSlug/groups'
    | '/diagnostics/$providerSlug/$diagnosticSlug/values'
    | '/diagnostics/$providerSlug/$diagnosticSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/content'
    | '/content/about'
    | '/content/privacy'
    | '/content/terms-of-use'
    | '/datasets/$slug'
    | '/executions/$groupId'
    | '/explorer/themes'
    | '/datasets'
    | '/diagnostics'
    | '/executions'
    | '/explorer'
    | '/diagnostics/$providerSlug/$diagnosticSlug/figures'
    | '/diagnostics/$providerSlug/$diagnosticSlug/groups'
    | '/diagnostics/$providerSlug/$diagnosticSlug/values'
    | '/diagnostics/$providerSlug/$diagnosticSlug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/content'
    | '/_app/explorer'
    | '/content/about'
    | '/content/privacy'
    | '/content/terms-of-use'
    | '/_app/datasets/$slug'
    | '/_app/executions/$groupId'
    | '/_app/explorer/themes'
    | '/_app/datasets/'
    | '/_app/diagnostics/'
    | '/_app/executions/'
    | '/_app/explorer/'
    | '/_app/diagnostics/$providerSlug/$diagnosticSlug'
    | '/_app/diagnostics/$providerSlug/$diagnosticSlug/figures'
    | '/_app/diagnostics/$providerSlug/$diagnosticSlug/groups'
    | '/_app/diagnostics/$providerSlug/$diagnosticSlug/values'
    | '/_app/diagnostics/$providerSlug/$diagnosticSlug/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ContentRouteRoute: typeof ContentRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ContentRouteRoute: ContentRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/content"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app/route.tsx",
      "children": [
        "/_app/explorer",
        "/_app/datasets/$slug",
        "/_app/executions/$groupId",
        "/_app/datasets/",
        "/_app/diagnostics/",
        "/_app/executions/",
        "/_app/diagnostics/$providerSlug/$diagnosticSlug"
      ]
    },
    "/content": {
      "filePath": "content/route.tsx",
      "children": [
        "/content/about",
        "/content/privacy",
        "/content/terms-of-use"
      ]
    },
    "/_app/explorer": {
      "filePath": "_app/explorer/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/explorer/themes",
        "/_app/explorer/"
      ]
    },
    "/content/about": {
      "filePath": "content/about.tsx",
      "parent": "/content"
    },
    "/content/privacy": {
      "filePath": "content/privacy.ts",
      "parent": "/content"
    },
    "/content/terms-of-use": {
      "filePath": "content/terms-of-use.ts",
      "parent": "/content"
    },
    "/_app/datasets/$slug": {
      "filePath": "_app/datasets.$slug.tsx",
      "parent": "/_app"
    },
    "/_app/executions/$groupId": {
      "filePath": "_app/executions.$groupId.tsx",
      "parent": "/_app"
    },
    "/_app/explorer/themes": {
      "filePath": "_app/explorer/themes.tsx",
      "parent": "/_app/explorer"
    },
    "/_app/datasets/": {
      "filePath": "_app/datasets.index.tsx",
      "parent": "/_app"
    },
    "/_app/diagnostics/": {
      "filePath": "_app/diagnostics.index.tsx",
      "parent": "/_app"
    },
    "/_app/executions/": {
      "filePath": "_app/executions.index.tsx",
      "parent": "/_app"
    },
    "/_app/explorer/": {
      "filePath": "_app/explorer/index.tsx",
      "parent": "/_app/explorer"
    },
    "/_app/diagnostics/$providerSlug/$diagnosticSlug": {
      "filePath": "_app/diagnostics.$providerSlug.$diagnosticSlug/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/diagnostics/$providerSlug/$diagnosticSlug/figures",
        "/_app/diagnostics/$providerSlug/$diagnosticSlug/groups",
        "/_app/diagnostics/$providerSlug/$diagnosticSlug/values",
        "/_app/diagnostics/$providerSlug/$diagnosticSlug/"
      ]
    },
    "/_app/diagnostics/$providerSlug/$diagnosticSlug/figures": {
      "filePath": "_app/diagnostics.$providerSlug.$diagnosticSlug/figures.tsx",
      "parent": "/_app/diagnostics/$providerSlug/$diagnosticSlug"
    },
    "/_app/diagnostics/$providerSlug/$diagnosticSlug/groups": {
      "filePath": "_app/diagnostics.$providerSlug.$diagnosticSlug/groups.tsx",
      "parent": "/_app/diagnostics/$providerSlug/$diagnosticSlug"
    },
    "/_app/diagnostics/$providerSlug/$diagnosticSlug/values": {
      "filePath": "_app/diagnostics.$providerSlug.$diagnosticSlug/values.tsx",
      "parent": "/_app/diagnostics/$providerSlug/$diagnosticSlug"
    },
    "/_app/diagnostics/$providerSlug/$diagnosticSlug/": {
      "filePath": "_app/diagnostics.$providerSlug.$diagnosticSlug/index.tsx",
      "parent": "/_app/diagnostics/$providerSlug/$diagnosticSlug"
    }
  }
}
ROUTE_MANIFEST_END */
