/**
 * Long names for the IPCC AR6 reference regions (Iturbide et al. 2020).
 * Diagnostics store the short code, so the code stays the value and this only shapes the label.
 */
const IPCC_REGION_NAMES: Record<string, string> = {
  GIC: "Greenland and Iceland",
  NWN: "North-Western North America",
  NEN: "North-Eastern North America",
  WNA: "Western North America",
  CNA: "Central North America",
  ENA: "Eastern North America",
  NCA: "Northern Central America",
  SCA: "Southern Central America",
  CAR: "Caribbean",
  NWS: "North-Western South America",
  NSA: "Northern South America",
  NES: "North-Eastern South America",
  SAM: "South American Monsoon",
  SWS: "South-Western South America",
  SES: "South-Eastern South America",
  SSA: "Southern South America",
  NEU: "Northern Europe",
  WCE: "Western and Central Europe",
  EEU: "Eastern Europe",
  MED: "Mediterranean",
  SAH: "Sahara",
  WAF: "Western Africa",
  CAF: "Central Africa",
  NEAF: "North-Eastern Africa",
  SEAF: "South-Eastern Africa",
  WSAF: "Western Southern Africa",
  ESAF: "Eastern Southern Africa",
  MDG: "Madagascar",
  RAR: "Russian Arctic",
  WSB: "Western Siberia",
  ESB: "Eastern Siberia",
  RFE: "Russian Far East",
  WCA: "Western Central Asia",
  ECA: "Eastern Central Asia",
  TIB: "Tibetan Plateau",
  EAS: "Eastern Asia",
  ARP: "Arabian Peninsula",
  SAS: "Southern Asia",
  SEA: "South-Eastern Asia",
  NAU: "Northern Australia",
  CAU: "Central Australia",
  EAU: "Eastern Australia",
  SAU: "Southern Australia",
  NZ: "New Zealand",
  EAN: "Eastern Antarctica",
  WAN: "Western Antarctica",
  ARO: "Arctic Ocean",
  NPO: "North Pacific Ocean",
  EPO: "Equatorial Pacific Ocean",
  SPO: "South Pacific Ocean",
  NAO: "North Atlantic Ocean",
  EAO: "Equatorial Atlantic Ocean",
  SAO: "South Atlantic Ocean",
  ARS: "Arabian Sea",
  BOB: "Bay of Bengal",
  EIO: "Equatorial Indian Ocean",
  SIO: "Southern Indian Ocean",
  SOO: "Southern Ocean",
};

/** The long name for a region code, or the code itself when it is not an AR6 region. */
export function ipccRegionName(code: string): string {
  return IPCC_REGION_NAMES[code] ?? code;
}
