name: CI

on:
  pull_request:
  push:
    branches: [main]
    tags: ['v*']


jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4


  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup Biome
      uses: biomejs/setup-biome@v2
      with:
        version: latest

    - name: Run Biome
      run: biome ci .

#    - name: Run tests
#      run: npm run test

    - name: Build
      run: npm run build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/setup

    - name: Run linting
      continue-on-error: true
      run: |
        uv run ruff check .

    - name: Run tests
      continue-on-error: true
      run: |
        pytest tests/

